In [1]:
import numpy as np

In [22]:
theta = np.pi / 2

In [23]:
rotated_matrix = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
reversed_matrix = np.array([[np.cos(theta), np.sin(theta)], [-np.sin(theta), np.cos(theta)]])

In [30]:
np.arange(3) @ np.arange(9).reshape(3, 3)

array([15, 18, 21])

In [19]:
rotated_matrix @ reversed_matrix

array([[ 1.00000000e+00, -4.26642159e-17],
       [-4.26642159e-17,  1.00000000e+00]])

In [24]:
rotated_matrix

array([[ 6.123234e-17, -1.000000e+00],
       [ 1.000000e+00,  6.123234e-17]])

In [ ]:
rotated_matrix.

In [25]:
reversed_matrix

array([[ 6.123234e-17,  1.000000e+00],
       [-1.000000e+00,  6.123234e-17]])

In [ ]:
torch.Size([64, 20, 8, 8]) torch.Size([64, 20, 8])

In [45]:
np.matmul(np.arange(64 * 20 * 8 * 8).reshape(64, 20, 8, 8), np.arange(64 * 20 * 8).reshape(64, 20, 8, 1)).shape

(64, 20, 8, 1)